name: CI - Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Устанавливаем .NET SDK (версия 8.0)
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # 3️⃣ Восстанавливаем зависимости
      - name: Restore dependencies
        run: dotnet restore ./FilestoreMicroS.sln

      # 4️⃣ Сборка проекта
      - name: Build solution
        run: dotnet build ./FilestoreMicroS.sln --configuration Release --no-restore

      # 5️⃣ Запуск тестов (из проекта FilestoreMicroS.Tests)
      - name: Run tests
        run: dotnet test ./FilestoreMicroS.Tests/FilestoreMicroS.Tests.csproj --no-build --verbosity normal
