name: CI/CD - Build, Test and Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore FilestoreMicroS/FilestoreMicroS.sln

      - name: Build solution
        run: dotnet build FilestoreMicroS/FilestoreMicroS.sln --configuration Debug --no-restore

      - name: Run tests with coverage
        run: |
          dotnet test FilestoreMicroS.Tests/FilestoreMicroS.Tests.csproj \
            --configuration Debug \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=opencover \
            /p:CoverletOutput=./TestResults/coverage.xml
            '/p:ExcludeByFile=**/Migrations/*.cs'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./FilestoreMicroS.Tests/TestResults/coverage.xml
          fail_ci_if_error: true
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t gefakra/filestoremicros:latest .
          docker push gefakra/filestoremicros:latest   
