name: CI/CD - Build, Test and Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore FilestoreMicroS/FilestoreMicroS.sln

      - name: Build solution
        run: dotnet build FilestoreMicroS/FilestoreMicroS.sln --configuration Debug --no-restore

      - name: Run tests
        run: dotnet test FilestoreMicroS.Tests/FilestoreMicroS.Tests.csproj --configuration Debug --logger "console;verbosity=detailed"

      - name: Build and push Docker image
        if: success()
        run: |
          docker build -t gefakra/filestoremicros:latest .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push gefakra/filestoremicros:latest
